---
# Enable IPv4 packet forwarding 
- name: Set sysctl parameters in k8s.conf
  copy:
    content: |
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  notify: Reload sysctl

# Install Containerd
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Add Docker repository
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
    
- name: Install containerd
  yum:
    name: containerd
    state: present

- name: Start containerd
  service:
    name: containerd
    state: started
    enabled: yes

# Configuring the systemd cgroup driver
- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    executable: /bin/bash

- name: Set SystemdCgroup to true in containerd config
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup'
    line: '            SystemdCgroup = true'
    backrefs: yes

- name: Restart containerd to apply changes
  service:
    name: containerd
    state: restarted