---
- name: Install containerd, kubeadm
  hosts: all
  become: yes
  roles:
    - role: containerd
    - role: kubeadm

- name: Init-cluster
  hosts: master
  become: yes
  roles:
    - role: init-cluster

- name: Join worker nodes
  hosts: worker
  become: yes
  tasks:
    - name: Join worker nodes
      command: "{{ hostvars[groups['master'][0]].join_token_out }}"